Wed 27 Mar 2019 21:16:47 GMT

diff --git a/scripts/i3exit b/scripts/i3exit
--- a/scripts/i3exit
+++ b/scripts/i3exit
@@ -5,31 +5,31 @@
 [[ $(cat /proc/1/comm) == "systemd" ]] && logind=systemctl || logind=loginctl
 
 case "$1" in
-    lock)
-        dm-tool lock
-        ;;
-    logout)
-        i3-msg exit
-        ;;
-    switch_user)
-        dm-tool switch-to-greeter
-        ;;
-    suspend)
-        dm-tool lock && $logind suspend
-        ;;
-    hibernate)
-        dm-tool lock && $logind hibernate
-        ;;
-    reboot)
-        $logind reboot
-        ;;
-    shutdown)
-        $logind poweroff
-        ;;
-    *)
-        echo "== ! i3exit: missing or invalid argument ! =="
-        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
-        exit 2
+	lock)
+		dm-tool lock
+		;;
+	logout)
+		i3-msg exit
+		;;
+	switch_user)
+		dm-tool switch-to-greeter
+		;;
+	suspend)
+		dm-tool lock && $logind suspend
+		;;
+	hibernate)
+		dm-tool lock && $logind hibernate
+		;;
+	reboot)
+		$logind reboot
+		;;
+	shutdown)
+		$logind poweroff
+		;;
+	*)
+		echo "== ! i3exit: missing or invalid argument ! =="
+		echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
+		exit 2
 esac
 
 exit 0
